/*
 * AREA_HANDLER AUTOGENERATED ROOM
 *
 * DO NOT CHANGE ANYTHING IN THIS ROOM SINCE THE ROOM
 * AUTOREMOVES ITSELF REGULARLY.
 */

inherit "/std/room";

#include <stdproperties.h>
#include <macros.h>
#define TO this_object()

string		Master_ob;	/* The master object */
int		Timeout;	/* Timeout time */
static int	Alarm;		/* Alarm ID */

public nomask void set_cleanup_time(int time);

create_room()
{
    setuid();
    seteuid(getuid());

